controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_health_check:
    path: /health
    controller: App\Controller\HealthController::check
    methods: [GET]
